name = "discord-bot"
main = "src/index.js"
compatibility_date = "2024-09-23"

# Add your secrets with:
# npx wrangler secret put DISCORD_TOKEN
# npx wrangler secret put DISCORD_PUBLIC_KEY
# npx wrangler secret put DISCORD_APPLICATION_ID
